class Voca {
  late String voca;
  late String mean;
  int? id ;

  Voca({required this.voca, required this.mean});


  Map<String,dynamic> toMap() {
    return {
      'voca' : voca,
      'mean' : mean,
      'id' : id ?? -1
    };
  }

  Voca.fromMap(Map<String,dynamic> map) {
    id = map['id'];
    voca = map['voca'];
    mean = map['mean'];
  }
  

   @override
  String toString() {
    return 'Voca{id: $id,voca: $voca, mean: $mean}';
  }

  static List<List<Map<String, String>>> days = [
    [],
    [
      {"voca": "resume", "mean": "이력서"},
      {"voca": "applicant", "mean": "지원자, 신청자"},
      {"voca": "requirement", "mean": "필요조건, 요건"},
      {"voca": "meet", "mean": "(필요,요구 등을)만족시키다"},
      {"voca": "qualified", "mean": "자격있는, 적격의"},
      {"voca": "candidate", "mean": "후보자, 지원자"},
      {"voca": "confidence", "mean": "확신, 자신, 신임"},
      {"voca": "highly", "mean": "매우, 대단히"},
      {"voca": "professional", "mean": "전문적인, 직업의, 전문가"},
      {"voca": "interview", "mean": "면접, 면접을 보다"},
      {"voca": "hire", "mean": "고용하다"},
      {"voca": "training", "mean": "교육, 훈련"},
      {"voca": "reference", "mean": "추천서, 참고"},
      {"voca": "position", "mean": "일자리, 직책, 두다"},
      {"voca": "achievement", "mean": "성취, 달성"},
      {"voca": "impressed", "mean": "인상 깊게 생각하는, 감명을 받은"},
      {"voca": "excellent", "mean": "훌륭한"},
      {"voca": "eligible", "mean": "자격이 있는, 적격의"},
      {"voca": "identify", "mean": "알아보다, 확인하다"},
      {"voca": "associate", "mean": "관련시키다"},
      {"voca": "condition", "mean": "조건"},
      {"voca": "employment", "mean": "고용"},
      {"voca": "lack", "mean": "~이 없다, 부족"},
      {"voca": "managerial", "mean": "관리의"},
      {"voca": "diligent", "mean": "성실한"},
      {"voca": "familiar", "mean": "익숙한, 친숙한"},
      {"voca": "proficiency", "mean": "숙달, 능숙"},
      {"voca": "prospective", "mean": "장래의, 미래의"},
      {"voca": "appeal", "mean": "관심을 끌다, 매력적이다"},
      {"voca": "specialize", "mean": "~을 전공하다, 전문적으로 다루다"},
      {"voca": "apprehensive", "mean": "걱정하는, 염려하는"},
      {"voca": "consultant", "mean": "고문, 컨설턴트"},
      {"voca": "entitle", "mean": "자격을 주다"},
      {"voca": "degree", "mean": "학위"},
      {"voca": "payroll", "mean": "임금대장, 금료명부"},
      {"voca": "recruit", "mean": "(신입사원등을)모집하다"},
      {"voca": "certification", "mean": "증명서, 증명"},
      {"voca": "occupation", "mean": "직업"},
      {"voca": "wage", "mean": "임금, 급료"}
    ],
    [
      {"voca": "attire", "mean": "복장, 옷차림새"},
      {"voca": "code", "mean": "규범, 관례;암호"},
      {"voca": "concern", "mean": "우려, 걱정, 문제, 일, ~을 걱정스럽게 하다; 영향을 미치다, 관련되다."},
      {"voca": "policy", "mean": "규정; 보험, 증권"},
      {"voca": "comply", "mean": "준수하다, 따르다"},
      {"voca": "regulation", "mean": "규정"},
      {"voca": "exception", "mean": "예외"},
      {"voca": "adhere", "mean": "지키다, 고수하다"},
      {"voca": "severely", "mean": "엄격하게, 심하게"},
      {"voca": "refrain", "mean": "자제하다, 삼가다"},
      {"voca": "permission", "mean": "허락, 허가"},
      {"voca": "access", "mean": "이용권한, 접근;통로, ~에 접근하다, 도달하다"},
      {"voca": "thoroughly", "mean": "철저하게, 완전히, 대단히"},
      {"voca": "revise", "mean": "(의견, 계획을)수정하다, 변경하다"},
      {"voca": "approach", "mean": "접근법, 처리방법"},
      {"voca": "approval", "mean": "승인, 인가"},
      {"voca": "form", "mean": "종류, 유형, 양식"},
      {"voca": "immediately", "mean": "즉시, 곧"},
      {"voca": "inspection", "mean": "점검, 검사"},
      {"voca": "arrangement", "mean": "준비, 마련, 주선"},
      {"voca": "procedure", "mean": "절차"},
      {"voca": "negative", "mean": "부정적인, 비관적인"},
      {"voca": "mandate", "mean": "명령하다, 지시하다, 권한, 지시, 명령"},
      {"voca": "effect", "mean": "(법률등의)효력, 효과, 영향, 결과로서 ~을 가져오다"},
      {"voca": "drastically", "mean": "심하게, 과감하게, 철저하게"},
      {"voca": "according to", "mean": "~에 따라"},
      {"voca": "enable", "mean": "(무엇을)가능하게 하다"},
      {"voca": "standard", "mean": "기준, 표준"},
      {"voca": "constant", "mean": "지속적인, 끊임없이 계속하는"},
      {"voca": "act", "mean": "법령, 결의서; 행위, 행동, 결정하다, 판결을 내리다, 행동하다"},
      {"voca": "compensation", "mean": "보상금, 보상"},
      {"voca": "ban", "mean": "금지, 금지하다"},
      {"voca": "obligation", "mean": "의무, 책임"},
      {"voca": "authorize", "mean": "~을 인가하다, 권한을 부여하다."},
      {"voca": "prohibit", "mean": "금지하다"},
      {"voca": "abolish", "mean": "(제도, 법률등을)폐지하다"},
      {"voca": "enforce", "mean": "(법률을)시행하다, 집행하다"},
      {"voca": "habit", "mean": "습관, 버릇"},
      {"voca": "lagislation", "mean": "법률, 법규"},
      {"voca": "restrict", "mean": "한정하다, 제한하다"}
    ],
    [
      {"voca": "accustomed", "mean": "익숙한"},
      {"voca": "corporatiion", "mean": "주식회사, 법인"},
      {"voca": "demanding", "mean": "요구가 많은, 힘든"},
      {"voca": "colleague", "mean": "동료"},
      {"voca": "division", "mean": "부서"},
      {"voca": "request", "mean": "요청, 요청하다"},
      {"voca": "efficiently", "mean": "효율적으로"},
      {"voca": "manage", "mean": "~을 경영하다; 가까스로 하다"},
      {"voca": "submit", "mean": "제출하다"},
      {"voca": "directly", "mean": "곧바로"},
      {"voca": "remind", "mean": "~에게 상기시키다, 일깨우다"},
      {"voca": "instruct", "mean": "지시하다, 가르치다"},
      {"voca": "deadline", "mean": "마감일, 마감 시간"},
      {"voca": "sample", "mean": "견본, 샘플, 표본\r\n시식하다, (견본으로 질을)시험하다"},
      {"voca": "notify", "mean": "~에게 통지하다, 알리다"},
      {"voca": "perform", "mean": "행하다, 실행하다"},
      {"voca": "monitor", "mean": "감독하다, 감시하다, 실행하다"},
      {"voca": "deserve", "mean": "~할 만하다, ~할 가치가 있다"},
      {"voca": "assignment", "mean": "일, 임무, 과제"},
      {"voca": "entire", "mean": "전체의"},
      {"voca": "release", "mean": "발표하다, 공개하다, 출시, 발매"},
      {"voca": "extension", "mean": "연장, 연기; (전화의)내선"},
      {"voca": "electronically", "mean": "컴퓨터 통신망으로, 컴퓨터로"},
      {"voca": "attendance", "mean": "출석, 출근"},
      {"voca": "absolutely", "mean": "절대적으로, 완전히"},
      {"voca": "delegate", "mean": "(권한등을)위임하다. 대표"},
      {"voca": "attentively", "mean": "주의 깊게, 조심스럽게"},
      {"voca": "supervision", "mean": "감독"},
      {"voca": "workshop", "mean": "워크숍, 연수"},
      {"voca": "draw", "mean": "끌다, 끌어당기다"},
      {"voca": "revision", "mean": "수정, 개정"},
      {"voca": "reluctantly", "mean": "마지못해, 꺼려하여"},
      {"voca": "acquaint", "mean": "~에게 숙지시키다, 잘 알게 하다"},
      {"voca": "convey", "mean": "(용건을)전달하다"},
      {"voca": "check", "mean": "검사하다, 조사하다, 확인하다"},
      {"voca": "headquarters", "mean": "본부"},
      {
        "voca": "file",
        "mean": "(서류를)정리하다, 철하다;\r\n(서류, 신청, 고소 등을)정식으로 제기하다, 제출하다"
      },
      {"voca": "oversee", "mean": "감독하다 (foresee예견하다, oversea해외의)"},
      {"voca": "involved", "mean": "관여하는, 관계된, 연루된"},
      {"voca": "concentrate", "mean": "집중하다, 집중시키다"}
    ],
    [
      {"voca": "lax", "mean": "(행동 등이)느슨한, 규율에 못 미치는"},
      {"voca": "procrastinate", "mean": "미루다, 꾸물거리다"},
      {"voca": "combined", "mean": "결합된, 합동의"},
      {"voca": "accomplish", "mean": "성취하다"},
      {"voca": "voluntarily", "mean": "자발적으로"},
      {"voca": "undertake", "mean": "(일을)떠맡다"},
      {"voca": "assume", "mean": "(증거는 없으나)사실이라고 생각하다;\r\n(책임,역할을)맡다"},
      {"voca": "occasionally", "mean": "가끔, 때때로"},
      {"voca": "employee", "mean": "직원, 고용인"},
      {"voca": "assist", "mean": "돕다, 조력하다"},
      {"voca": "satisfied", "mean": "만족하는, 만족스러워하는"},
      {"voca": "manner", "mean": "방식, 태도"},
      {"voca": "responsible", "mean": "책임이 있는, 책임져야 할"},
      {"voca": "conduct", "mean": "(업무 등을)수행하다"},
      {"voca": "adjust", "mean": "적응하다"},
      {"voca": "personnel", "mean": "(집합적)직원, 인원; 인사과"},
      {"voca": "agree", "mean": "동의하다"},
      {"voca": "supervise", "mean": "감독하다, 지도하다"},
      {"voca": "coworker", "mean": "동료, 협력자"},
      {"voca": "direct", "mean": "~에게 길을 안내하다, 가르쳐 주다"},
      {"voca": "confidential", "mean": "기밀의, 내밀한"},
      {"voca": "assign", "mean": "배정하다, 할당하다"},
      {"voca": "leading", "mean": "선도적인, 일류의, 가장 중요한, 선두적인"},
      {"voca": "formal", "mean": "격식을 갖춘"},
      {"voca": "remove", "mean": "해임하다, 제거하다"},
      {"voca": "collect", "mean": "모으다"},
      {"voca": "coordinate", "mean": "조정하다"},
      {"voca": "hardly", "mean": "거의~하지않다"},
      {"voca": "abstract", "mean": "추상적인, 막연한"},
      {"voca": "directory", "mean": "주소록"},
      {"voca": "accountable", "mean": "책임이 있는"},
      {"voca": "skillfully", "mean": "능숙하게, 솜씨있게"},
      {"voca": "exclusive", "mean": "독점적인, 배타적인"},
      {"voca": "intention", "mean": "의지, 의향"},
      {"voca": "transform", "mean": "바꾸다, 변모시키다"},
      {"voca": "respectful", "mean": "정중한, 존중하는"},
      {"voca": "duplicate", "mean": "사본"},
      {"voca": "contrary", "mean": "반대"},
      {"voca": "disturbing", "mean": "충격적인, 불안감을 주는, 방해하는"},
      {"voca": "engage", "mean": "관여하다, 종사하다"},
      {"voca": "foster", "mean": "촉진하다, 육성하다"},
      {"voca": "neutrality", "mean": "중립성, 중립"},
      {"voca": "widely", "mean": "널리"}
    ],
    [
      {"voca": "sophisticated", "mean": "(기계가)정교한, 복잡한; 세련된"},
      {"voca": "timely", "mean": "시기적절한, 때를 맞춘"},
      {"voca": "realistically", "mean": "현실적으로"},
      {"voca": "promptly", "mean": "즉시; 정각에"},
      {"voca": "accessible", "mean": "출입할 수 있는; 이용할 수 있는"},
      {"voca": "implement", "mean": "실시하다, 실행하다"},
      {"voca": "feedback", "mean": "의견, 반응"},
      {"voca": "outstanding", "mean": "우수한; (부채 등이)미지불된"},
      {"voca": "inform", "mean": "~에게 알리다"},
      {"voca": "replacement", "mean": "교체, 후임자"},
      {"voca": "announcement", "mean": "공고, 발표"},
      {"voca": "department", "mean": "(조직, 기구의)부서"},
      {"voca": "permanently", "mean": "영구적으로, 불변으로"},
      {"voca": "fulfill", "mean": "(조건을)만족시키다, (약속, 의무등을)지키다, 이행하다"},
      {"voca": "outline", "mean": "개요, 설명하다, 약술하다"},
      {"voca": "explain", "mean": "설명하다"},
      {"voca": "contain", "mean": "포함하다"},
      {"voca": "compile", "mean": "(자료 등을)편집하다; 모으다"},
      {"voca": "subsequent", "mean": "차후의, 그 다음의"},
      {"voca": "overview", "mean": "개요, 개관"},
      {"voca": "provider", "mean": "공급자, 제공자"},
      {"voca": "matter", "mean": "문제, 일"},
      {"voca": "expertise", "mean": "전문지식, 전문기술"},
      {"voca": "demonstrate", "mean": "증명하다; (모형, 실험등으로)설명하다"},
      {"voca": "remainder", "mean": "나머지"},
      {"voca": "essential", "mean": "필수적인, 극히 중요한, 본질적인"},
      {"voca": "divide", "mean": "분배하다, 나누다"},
      {"voca": "major", "mean": "주요한, 중대한"},
      {"voca": "compliance", "mean": "(명령, 법규에의)준수"},
      {"voca": "clarify", "mean": "명확하게 하다"},
      {"voca": "face", "mean": "(문제 등에)직면하다; 향하다, 마주보다"},
      {"voca": "follow", "mean": "~을 따라가다; 주시하다; (분명히)이해하다"},
      {"voca": "aspect", "mean": "관점, 국면"},
      {"voca": "apparently", "mean": "보기에 ~한 듯한, 외관상으로는"},
      {"voca": "aware", "mean": "알고 있는, 인식하고 있는"},
      {"voca": "extended", "mean": "(기간 등을)연장한, 장기간에 걸친"},
      {"voca": "accidentally", "mean": "뜻하지 않게, 우연히"},
      {"voca": "advisable", "mean": "바람직한, 합당한"},
      {"voca": "concerned", "mean": "염려하는, 걱정하는; 관련된"},
      {"voca": "speak", "mean": "이야기 하다"}
    ],
    [
      {"voca": "collection", "mean": "소장품, 수집물; 징수, 수금"},
      {"voca": "exhibition", "mean": "전시회"},
      {"voca": "celebrity", "mean": "유명인사, 명사"},
      {"voca": "live", "mean": "(라디오, TV가)생방송인"},
      {"voca": "improvise", "mean": "(연주, 연설 등을)즉흥적으로 하다, 즉석에서 만들다."},
      {"voca": "popular", "mean": "인기있는"},
      {"voca": "donation", "mean": "기증, 기부"},
      {"voca": "alumni", "mean": "동창생들, 졸업생들"},
      {"voca": "present", "mean": "제시하다, 현재의, 참석한"},
      {"voca": "admission", "mean": "입장"},
      {"voca": "banquet", "mean": "연회, 만찬"},
      {"voca": "anniversary", "mean": "기념일"},
      {"voca": "required", "mean": "필수의, 의무적인"},
      {"voca": "succeed", "mean": "성공하다, 뒤를 잇다"},
      {"voca": "rest", "mean": "쉬다,휴식, 나머지"},
      {"voca": "fund-raising", "mean": "모금"},
      {"voca": "resume", "mean": "재개하다, 다시 시작하다"},
      {"voca": "issue", "mean": "(출판물의)제 ~호; 문제, 쟁점"},
      {"voca": "subscription", "mean": "(정기발행물의) 구독"},
      {"voca": "appear", "mean": "나타나다, 출현하다"},
      {"voca": "accompany", "mean": "동행하다, 동반하다"},
      {"voca": "edition", "mean": "(간행물의)판"},
      {"voca": "specifically", "mean": "명확하게, 분명히; 특히, 특별히"},
      {"voca": "anonymous", "mean": "익명의, 이름을 모르는"},
      {"voca": "commit", "mean": "헌신하다, 전념하다"},
      {"voca": "information", "mean": "유익한, 정보를 주는"},
      {"voca": "audience", "mean": "청중, 관중"},
      {"voca": "author", "mean": "작가, 저자"},
      {"voca": "note", "mean": "주목하다; 특별히 언급하다."},
      {"voca": "antique", "mean": "골동품"},
      {"voca": "manuscript", "mean": "원고"},
      {"voca": "beneficial", "mean": "유익한, 이로운"},
      {"voca": "upcoming", "mean": "곧 있을, 다가오는"},
      {"voca": "lend", "mean": "빌려주다"},
      {"voca": "current", "mean": "현재의,; 현행의, 통용되는"},
      {"voca": "local", "mean": "지방의, 고장의"},
      {"voca": "variety", "mean": "다양성, 변화"},
      {"voca": "advocate", "mean": "옹호자"},
      {"voca": "contributor", "mean": "기고가, 공헌자"},
      {"voca": "defy", "mean": "저항하다; (설명,묘사등이)거의 불가능하다"},
      {"voca": "fascinating", "mean": "매혹적인, 황홀한"},
      {"voca": "showing", "mean": "(영화, 연극의)상영; 전시"}
    ],
    [
      {"voca": "survey", "mean": "설문조사"},
      {"voca": "analysis", "mean": "분석"},
      {"voca": "respondent", "mean": "응답자"},
      {"voca": "competition", "mean": "경쟁"},
      {"voca": "consistently", "mean": "항상, 일관되게"},
      {"voca": "demand", "mean": "수요, 요구하다"},
      {"voca": "do one's utmost", "mean": "전력을 다하다"},
      {"voca": "expand", "mean": "확장하다, 확대하다"},
      {"voca": "advanced", "mean": "고급의; 진보한, 앞선"},
      {"voca": "postpone", "mean": "연기하다, 뒤로 미루다"},
      {"voca": "additional", "mean": "추가의, 부가적인"},
      {"voca": "appreciate", "mean": "고맙게 생각하다; 높이 평가하다; 감상하다"},
      {"voca": "demonstration", "mean": "설명; 드러냄, 시연"},
      {"voca": "buy", "mean": "사다, 구입하다"},
      {"voca": "examine", "mean": "조사하다"},
      {"voca": "effective", "mean": "효과적인; (법률 등이)발표되는, 시행되는"},
      {"voca": "like", "mean": "좋아하다"},
      {"voca": "especially", "mean": "특히"},
      {"voca": "closely", "mean": "면밀히, 엄밀히"},
      {"voca": "reserve", "mean": "예약하다, 지정하다; 보존하다"},
      {"voca": "cooperate", "mean": "협력하다, 협동하다"},
      {"voca": "very", "mean": "매우, 대단히, 아주"},
      {"voca": "consecutive", "mean": "연속적인"},
      {"voca": "expectation", "mean": "예상, 기대"},
      {"voca": "publicize", "mean": "공표하다; 광고하다, 선전하다"},
      {"voca": "raise", "mean": "높이다, 올리다; (의문을)제기하다"},
      {"voca": "extremely", "mean": "극도로, 대단히"},
      {"voca": "affect", "mean": "~에 영향을 미치다, 불리하게 작용하다"},
      {"voca": "target", "mean": "목표, 목표로 삼다"},
      {"voca": "campaign", "mean": "운동, 캠페인"},
      {"voca": "probable", "mean": "개연성이 높은, 유망한"},
      {"voca": "focus", "mean": "집중시키다, 집중하다"},
      {"voca": "seasonal", "mean": "계절의, 계절적인"},
      {"voca": "impact", "mean": "영향, 충격"},
      {"voca": "comparison", "mean": "비교"},
      {"voca": "gap", "mean": "격차"},
      {"voca": "mounting", "mean": "증가하는, 오르는"},
      {"voca": "reflective", "mean": "반영하는"}
    ],
    [
      {"voca": "advertisement", "mean": "광고"},
      {"voca": "marginal", "mean": "약간의; 주변의"},
      {"voca": "customer", "mean": "고객"},
      {"voca": "influence", "mean": "~에 영향을 주다, 영향"},
      {"voca": "instantly", "mean": "즉각적으로, 즉시"},
      {"voca": "creative", "mean": "창조적인, 독창적인"},
      {"voca": "aggressively", "mean": "적극적으로"},
      {"voca": "aim", "mean": "~을 겨누다, 목표, 목적"},
      {"voca": "strategy", "mean": "전략"},
      {"voca": "indicate", "mean": "보여주다, 나타내다"},
      {"voca": "attract", "mean": "끌다, 유인하다"},
      {"voca": "experience", "mean": "경험, 체험, 체험하다, 경험하다"},
      {"voca": "analyze", "mean": "분석하다, 분석적으로 검토하다"},
      {"voca": "introduce", "mean": "(신제품을)발표하다, 소개하다"},
      {"voca": "advise", "mean": "조언해주다, 충고하다"},
      {"voca": "subscribe", "mean": "구독하다"},
      {"voca": "absence", "mean": "부재; 결근, 결석"},
      {"voca": "means", "mean": "방법, 수단"},
      {"voca": "prefer", "mean": "(다른 것보다)~을 더 좋아하다, 선호하다"},
      {"voca": "advantage", "mean": "이점, 강점"},
      {"voca": "forward", "mean": "앞으로, (물건, 정보를)보내다"},
      {"voca": "contemporary", "mean": "동시대의; 현대의, 당대의"},
      {"voca": "discussion", "mean": "토론, 토의"},
      {"voca": "initial", "mean": "처음의, 최초의"},
      {"voca": "steadily", "mean": "착실하게; 꾸준히"},
      {"voca": "necessarily", "mean": "반드시"},
      {"voca": "resolve", "mean": "(문제 등을)해결하다"},
      {"voca": "detect", "mean": "간파하다, 탐지하다"},
      {"voca": "intensify", "mean": "강화하다, 증대하다, 강렬하게 만들다."},
      {"voca": "favorably", "mean": "호의적으로; 순조롭게"},
      {"voca": "cover", "mean": "포함하다; 지불하다; 덮다"},
      {"voca": "less", "mean": "보다 적은, 덜한"},
      {"voca": "majority", "mean": "대부분, 대다수"},
      {"voca": "adopt", "mean": "채택하다"},
      {"voca": "largely", "mean": "주로, 대부분"},
      {"voca": "disregard", "mean": "소홀히 하다, 무시하다"},
      {"voca": "effort", "mean": "노력"},
      {"voca": "incentive", "mean": "혜택, 장려금"},
      {"voca": "need", "mean": "필요, 요구, 욕구, ~할 필요가 있다."},
      {"voca": "mastermind", "mean": "(계획 등의)입안자, 지도자"}
    ],
    [
      {"voca": "stagnant", "mean": "침체된, 불경기의, (stagnance침체, 정체, 불황)"},
      {"voca": "dramatically", "mean": "극적으로"},
      {"voca": "brisk", "mean": "활발한, 호황의"},
      {"voca": "unstable", "mean": "불안정한, 변하기 쉬운"},
      {"voca": "rapidly", "mean": "급속히, 빨리"},
      {"voca": "soar", "mean": "(물가 등이)폭등하다, 높이 치솟다"},
      {"voca": "assert", "mean": "단언하다, 주장하다 (assertion 단언, 주장)"},
      {"voca": "boost", "mean": "(경기를)부양시키다, 상승시키다"},
      {"voca": "analyst", "mean": "분석가"},
      {"voca": "potential", "mean": "잠재적인"},
      {"voca": "pleased", "mean": "만족해하는, 기쁜"},
      {"voca": "remain", "mean": "계속~한 상태이다; 아직 ~해야한다"},
      {"voca": "limited", "mean": "제한된, 한정된"},
      {"voca": "costly", "mean": "비용이 많이 드는, 손실이 큰"},
      {"voca": "particular", "mean": "특정한, 독특한, 세심한 (partocularly 특히)"},
      {"voca": "drastic", "mean": "과감한, 급격한"},
      {"voca": "evenly", "mean": "고르게, 균등하게"},
      {"voca": "evidence", "mean": "증거"},
      {"voca": "prospect", "mean": "전망, 예상 (prospective 장래의, 미래의, 기대되는)"},
      {"voca": "lead", "mean": "이글다, 지휘하다; (어떤 결과에)이르다"},
      {"voca": "fall", "mean": "(값, 가치가)하락하다"},
      {"voca": "period", "mean": "기간, 시기"},
      {"voca": "indicator", "mean": "지표, 지수"},
      {"voca": "industry", "mean": "산업"},
      {"voca": "likely", "mean": "~할 것 같은"},
      {"voca": "boom", "mean": "붐, 호황"},
      {"voca": "director", "mean": "임원, 책임자"},
      {"voca": "substitute", "mean": "대용품, 대신하다(substitution 대용, 대체)"},
      {"voca": "consequence", "mean": "결과"},
      {"voca": "fairly", "mean": "상당히, 꽤"},
      {"voca": "economical", "mean": "경제적인, 절약되는"},
      {"voca": "thrive", "mean": "번영하다, 성공하다"},
      {
        "voca": "implication",
        "mean": "영향, 밀접한 관계 (implicate 관련시키다, 관련되었음을 나타내다)"
      },
      {"voca": "wane", "mean": "감소, 감퇴"},
      {"voca": "prosperity", "mean": "번영 (prosper 번영하다)"},
      {"voca": "depression", "mean": "불황 (depress 하락시키다, 약하게하다)"},
      {"voca": "dwindle", "mean": "줄어들다, 감소되다"},
      {"voca": "impede", "mean": "저해하다, 방해하다"},
      {"voca": "promising", "mean": "유망한, 전망이 좋은"},
      {"voca": "adversity", "mean": "역경, 불운"}
    ],
    [
      {"voca": "purchase", "mean": "구매하다, 구매"},
      {"voca": "installment", "mean": "할부"},
      {"voca": "affordable", "mean": "(가격이)알맞은, 감당할 수 있는"},
      {"voca": "exactly", "mean": "정확히"},
      {"voca": "auction", "mean": "경매"},
      {"voca": "authentic", "mean": "진정한, 진짜의, 진품의"},
      {"voca": "charge", "mean": "요금,청구,금액;책임,의무\r\n~을 청구하다; (외상으로)달아놓다"},
      {"voca": "notice", "mean": "통지, 공고"},
      {"voca": "experienced", "mean": "경험이 있는, 노련한, 능숙한"},
      {
        "voca": "instruction",
        "mean": "설명, 지시 (instruct 가르치다, 지시하다, instructor교사, 강사)"
      },
      {"voca": "expert", "mean": "전문가, 전문가의, 전문적인"},
      {"voca": "warranty", "mean": "(품질 등의)보증, 보증서"},
      {"voca": "refund", "mean": "환불, 환불금"},
      {"voca": "subscriber", "mean": "가입자, 구독자"},
      {"voca": "delivery", "mean": "배달"},
      {"voca": "price", "mean": "가격"},
      {"voca": "receipt", "mean": "영수증"},
      {"voca": "offer", "mean": "제공하다, 제공,오퍼"},
      {"voca": "carefully", "mean": "주의깊게, 신중히"},
      {"voca": "benefit", "mean": "혜택, 이익, 혜택을 보다, 이익을 얻다"},
      {"voca": "exclusively", "mean": "오로지, 독점적으로"},
      {"voca": "description", "mean": "(제품등의)설명, 해설"},
      {"voca": "relatively", "mean": "상대적으로"},
      {"voca": "spare", "mean": "아끼다, 할애하다, 예비의, 여분의"},
      {"voca": "preparation", "mean": "준비, 대비"},
      {"voca": "area", "mean": "지역, 구역"},
      {"voca": "clearance", "mean": "정리, 없애기; 허가"},
      {"voca": "alter", "mean": "(성질, 형상을)고치다, 바꾸다"},
      {"voca": "apply", "mean": "적용하다; 지원하다"},
      {"voca": "mutually", "mean": "서로, 상호 간에 (mutuality 상호관계, 상호의존)"},
      {"voca": "method", "mean": "방식, 방법"},
      {"voca": "acceptable", "mean": "용인되는, 받아들일 수 있는;\r\n훌륭한, 만족스러운"},
      {"voca": "desire", "mean": "욕구, 갈망, 원하다, 바라다"},
      {
        "voca": "redeemable",
        "mean": "(현금,상품과)교환할 수 있는, 환급할 수 있는( redeem 상환하다)"
      },
      {"voca": "officially", "mean": "공식적으로"},
      {"voca": "consumption", "mean": "소비(량), 소모 (consumptive 소모적인)"},
      {"voca": "qualify", "mean": "~의 자격을 얻다"},
      {"voca": "fabric", "mean": "섬유, 천"},
      {"voca": "valid", "mean": "유효한"},
      {"voca": "vendor", "mean": "노점상, 가판대; 판매업체"}
    ],
    [
      {"voca": "research", "mean": "연구, 조사"},
      {"voca": "devise", "mean": "고안하다, 발명하다"},
      {"voca": "revolutionary", "mean": "혁명적인"},
      {"voca": "innovative", "mean": "혁신적인"},
      {"voca": "feature", "mean": "특징, 특색, 특징으로 삼다, 특별히 포함하다"},
      {"voca": "inspiration", "mean": "영감"},
      {"voca": "sufficiently", "mean": "충분히(sufficient 충분한, 충분)"},
      {"voca": "patent", "mean": "특허, 특허권, 특허품"},
      {"voca": "envision", "mean": "(장래의 일 등을)계획하다, 상상하다"},
      {"voca": "extend", "mean": "연장하다; (기간을)늘리다;\r\n(감사의 뜻을)말하다, 베풀다"},
      {"voca": "following", "mean": "~후에, 다음의, 다음에 오는"},
      {"voca": "intend", "mean": "~할 작정이다; 의도하다"},
      {"voca": "grant", "mean": "(인정하여 정식으로)수여하다, 주다,\r\n(연구비, 장학금등의)보조금"},
      {"voca": "allow", "mean": "~하게 하다, ~을 허락하다"},
      {"voca": "inspect", "mean": "~을 검사하다, 조사하다"},
      {"voca": "improve", "mean": "향상시키다, 개선하다"},
      {"voca": "increasingly", "mean": "점점, 더욱 더"},
      {"voca": "invest", "mean": "투자하다, 운용하다"},
      {"voca": "various", "mean": "여러 가지의, 가지각색의"},
      {"voca": "upgrade", "mean": "업그레이드, 개량형\r\n업그레이드하다, 개선하다"},
      {"voca": "manual", "mean": "설명서, 안내서"},
      {"voca": "explore", "mean": "조사하다, 탐구하다"},
      {"voca": "response", "mean": "응답, 대답"},
      {"voca": "appearance", "mean": "외관, 외모"},
      {"voca": "successful", "mean": "성공적인, 성공한"},
      {"voca": "hold", "mean": "~을 수용하다, ~을 담다;\r\n(회의 등을)개최하다, 열다"},
      {"voca": "advance", "mean": "진보, 전진"},
      {"voca": "reliable", "mean": "믿을 만한, 신뢰할 수 있는"},
      {"voca": "quality", "mean": "품질, 질"},
      {"voca": "domestic", "mean": "국내의, 국산의"},
      {"voca": "development", "mean": "개발, 발전"},
      {"voca": "availability", "mean": "(입수)가능성, 유효성, 유용성"},
      {"voca": "update", "mean": "갱신, 개정, 갱신하다,\r\n최신의 것으로 하다"},
      {"voca": "accurate", "mean": "정확한"},
      {"voca": "complicate", "mean": "복잡한(complicatedly복잡하게)"},
      {"voca": "accomplished", "mean": "숙련된, 노련한"},
      {"voca": "inquiry", "mean": "문의, 질문"},
      {"voca": "indication", "mean": "징후, 조짐"},
      {"voca": "manufacturer", "mean": "제조회사, 제조업자"},
      {"voca": "compatible", "mean": "호환되는, 양립할 수 있는(compatibility 양립성, 호환성)"},
      {"voca": "superior", "mean": "우수한, 상급의"},
      {"voca": "absolute", "mean": "완전한, 완전무결한"},
      {"voca": "broaden", "mean": "넓히다"},
      {"voca": "corrosion", "mean": "부식"}
    ],
    [
      {"voca": "epuipment", "mean": "장비, 설비"},
      {"voca": "automate", "mean": "자동화하다"},
      {"voca": "specification", "mean": "명세서, 설명서, 사양"},
      {"voca": "properly", "mean": "제대로, 정확하게"},
      {"voca": "safety", "mean": "안전"},
      {"voca": "precaution", "mean": "예방조치, 예방책"},
      {"voca": "operate", "mean": "(기계 등이)작동하다, 움직이다"},
      {"voca": "processing", "mean": "가공, 처리(process 과정, 진행, 처리하다)"},
      {"voca": "capacity", "mean": "용량, 수용력; 역할"},
      {"voca": "assemble", "mean": "(부품,기계 등을)조립하다;\r\n(사람을)모으다"},
      {"voca": "utilize", "mean": "이용하다, 활용하다"},
      {"voca": "place", "mean": "~을-한 상태에 두다;\r\n(지시,주문,신청등을)하다"},
      {"voca": "fill", "mean": "~을 채우다; (주문대로)이행하다"},
      {"voca": "manufacturing", "mean": "제조(업)의"},
      {"voca": "renovate", "mean": "(낡은 건물, 가구등을)개조하다,\r\n수리하다, 보수하다"},
      {"voca": "decision", "mean": "결정, 판단"},
      {"voca": "material", "mean": "재료, 물질"},
      {"voca": "success", "mean": "성과, 성공"},
      {"voca": "attribute", "mean": "(원인을)~의 덕분으로 돌리다"},
      {"voca": "efficiency", "mean": "효율, 능률"},
      {"voca": "limit", "mean": "한계, 제한"},
      {"voca": "tailored", "mean": "맞춤의, 주문에 따라 맞춘"},
      {"voca": "component", "mean": "부품, (구성)요소"},
      {"voca": "capable", "mean": "~을 할 수 있는, ~할 능력이 있는"},
      {"voca": "economize", "mean": "절약하다, 아끼다"},
      {"voca": "flexible", "mean": "융통성 있는; 유연한, 잘 구부러지는"},
      {"voca": "comparable", "mean": "필적하는, 비교되는"},
      {"voca": "produce", "mean": "생산하다"},
      {"voca": "respectively", "mean": "각각, 따로(respective 각각의)"},
      {"voca": "device", "mean": "장치"},
      {"voca": "trim", "mean": "(깍아)다듬다, 없애다; 삭감하다"},
      {"voca": "launch", "mean": "(신제품을)출시하다"},
      {"voca": "separately", "mean": "개별적으로, 따로따로"},
      {"voca": "expiration", "mean": "(기간,임기 등의)만료, 만기"},
      {"voca": "maneuver", "mean": "이동시키다, 움직이다"},
      {"voca": "coming", "mean": "다가오는"},
      {"voca": "damaged", "mean": "손상된, 손해를 입은"},
      {"voca": "prevent", "mean": "~을 막다, ~을 예방하다"},
      {"voca": "power", "mean": "전력, 전기"},
      {"voca": "chemical", "mean": "화학제품"}
    ],
    [
      {"voca": "complaint", "mean": "불평"},
      {"voca": "deal", "mean": "처리하다; 거래하다; 분배하다"},
      {"voca": "argumentative", "mean": "논쟁적인, 논쟁을 좋아하는"},
      {"voca": "appropriately", "mean": "적절하게(appropriate 적합한)"},
      {"voca": "respond", "mean": "응답하다"},
      {"voca": "infuriate", "mean": "화나게하다, 격분시키다"},
      {"voca": "curteous", "mean": "예의바른"},
      {"voca": "satisfaction", "mean": "만족"},
      {"voca": "inconvenience", "mean": "불편, ~에게 불편을 느끼게 하다"},
      {"voca": "complete", "mean": "완료하다, 완성하다, 완료된, 완성된"},
      {"voca": "specific", "mean": "구체적인, 명확한"},
      {"voca": "return", "mean": "반환하다, 반송하다"},
      {"voca": "replace", "mean": "~을 교체하다, 대체하다"},
      {"voca": "presentation", "mean": "발표"},
      {"voca": "evaluation", "mean": "평가"},
      {"voca": "confident", "mean": "자신 있는"},
      {"voca": "cause", "mean": "~을 야기하다, ~의 원인이 되다\r\n원인"},
      {"voca": "commentary", "mean": "해설, 설명(comment 해설하다,논평, 주석을달다)"},
      {"voca": "notification", "mean": "통지"},
      {"voca": "apologize", "mean": "사과하다"},
      {"voca": "interact", "mean": "소통하다, 교류하다; 상호작용을 하다"},
      {"voca": "certain", "mean": "확신하는, 확실한; 특정한"},
      {"voca": "commitment", "mean": "헌신, 전념"},
      {"voca": "applaud", "mean": "~에게 박수를 보내다; 칭찬하다"},
      {"voca": "biography", "mean": "약력, 전기"},
      {"voca": "critical", "mean": "비판적인; 중요한; 위기의"},
      {"voca": "depend on", "mean": "~에 달려 있다, ~에게 의존하다"},
      {"voca": "combine", "mean": "결합시키다"},
      {"voca": "priority", "mean": "우선권, 우선사항"},
      {"voca": "observe", "mean": "관찰하다, 주시하다;\r\n(규칙 등을)준수하다, 지키다"},
      {"voca": "defective", "mean": "결함이 있는"},
      {"voca": "reflect", "mean": "반영하다, 나타내다"},
      {"voca": "attitude", "mean": "태도, 마음가짐"},
      {"voca": "disappoint", "mean": "실망시키다"},
      {"voca": "inquire", "mean": "문의하다, 질문하다"},
      {"voca": "insert", "mean": "삽입하다"},
      {"voca": "disclose", "mean": "공개하다, 드러내다"},
      {"voca": "guarantee", "mean": "보장하다, 보장"},
      {"voca": "politely", "mean": "공손하게, 예의바르게"},
      {"voca": "seriously", "mean": "진지하게"}
    ],
    [
      {"voca": "international", "mean": "국제적인"},
      {"voca": "attraction", "mean": "관광 명소"},
      {"voca": "itinerary", "mean": "여행 일정"},
      {"voca": "exotic", "mean": "이국적인, 매혹적인"},
      {"voca": "diverse", "mean": "다양한"},
      {"voca": "superb", "mean": "최고의, 뛰어난"},
      {"voca": "baggage", "mean": "수화물"},
      {"voca": "destination", "mean": "목적지"},
      {"voca": "missing", "mean": "분실된, 없어진"},
      {"voca": "locate", "mean": "(~의 위치를)찾아내다;\r\n~을 위치시키다"},
      {"voca": "approximately", "mean": "대략"},
      {"voca": "duty", "mean": "관세,세금; 직무,의무"},
      {"voca": "process", "mean": "과정, 처리하다"},
      {"voca": "board", "mean": "탑승하다, 이사회"},
      {"voca": "comfortable", "mean": "편안한"},
      {"voca": "declare", "mean": "(세관에서)신고하다"},
      {"voca": "specify", "mean": "명시하다 (specification 열거, 명시, 명세서)"},
      {"voca": "depart", "mean": "출발하다"},
      {"voca": "emergency", "mean": "비상시, 비상 사태"},
      {"voca": "passenger", "mean": "승객"},
      {"voca": "outgoing", "mean": "(장소를)출발하는, 떠나는;\r\n(지위를)떠나는"},
      {"voca": "tighly", "mean": "단단히, 꽉"},
      {"voca": "tour", "mean": "(공장,시설 등의)견학, 짧은 여행"},
      {"voca": "carrier", "mean": "항공사, 수송기, 수송 회사"},
      {"voca": "customarily", "mean": "관례상, 습관적으로"},
      {"voca": "confuse", "mean": "혼란시키다 (refuse 거절하다, 거부하다)"},
      {"voca": "arrive", "mean": "도착하다"},
      {"voca": "brochure", "mean": "(홍보용)소책자, 브로셔"},
      {"voca": "involve", "mean": "수반하다, 포함하다; 참여시키다"},
      {"voca": "ship", "mean": "(배나 다른 운송 수단으로)운송하다, 수송하다, 선박, 배"},
      {"voca": "suitcase", "mean": "여행가방"},
      {"voca": "unavailable", "mean": "이용할 수 없는, 구할 수 없는"},
      {"voca": "fill out/in", "mean": "(서류에)기입하다, 적어 넣다"},
      {"voca": "customs", "mean": "세관"},
      {"voca": "away", "mean": "떨어져서"},
      {"voca": "dramatic", "mean": "멋진, 극적인; 급격한"},
      {"voca": "hospitality", "mean": "환대, 친절"},
      {"voca": "indulge", "mean": "빠지다, 탐닉하다"},
      {"voca": "proximity", "mean": "가까움, 근접함"},
      {"voca": "seating", "mean": "(집합적)좌석 설비; 좌석 배열"},
      {"voca": "unlimited", "mean": "무제한의"}
    ],
    [
      {"voca": "proposal", "mean": "제안, 계획"},
      {"voca": "alliance", "mean": "동맹, 제휴"},
      {"voca": "stipulation", "mean": "계약 조건"},
      {"voca": "term", "mean": "조건; 임기, 기한"},
      {"voca": "compromise", "mean": "타협, 화해"},
      {"voca": "negotiation", "mean": "협상, 교섭"},
      {"voca": "agreement", "mean": "계약, 협정; 합의"},
      {"voca": "deadlock", "mean": "교착 상태"},
      {"voca": "review", "mean": "검토하다, 재조사하다"},
      {"voca": "contract", "mean": "계약(서),계약하다, 수축하다"},
      {"voca": "signature", "mean": "서명"},
      {"voca": "originally", "mean": "원래, 처음에는"},
      {"voca": "direction", "mean": "방향, 지시, 감독"},
      {"voca": "initially", "mean": "처음에, 초기에"},
      {"voca": "expire", "mean": "(계약등이)만료되다"},
      {"voca": "collaborate", "mean": "협력하다, 공동으로 일하다"},
      {"voca": "dedicate", "mean": "전념하다, 헌신하다, 바치다(indicate 나타내다)"},
      {"voca": "revised", "mean": "수정된, 변경된"},
      {"voca": "imperative", "mean": "반드시 해야 하는, 필수적인"},
      {"voca": "cooperatively", "mean": "협력하여, 협조적으로"},
      {"voca": "commission", "mean": "수수료, 커미션; 위원회\r\n(일 등을)의뢰하다, 주문하다"},
      {"voca": "omit", "mean": "빠뜨리다, 생략하다"},
      {"voca": "conflict", "mean": "대립, 충돌, 갈등"},
      {"voca": "renew", "mean": "(계약 등을)갱신하다"},
      {"voca": "proficient", "mean": "능숙한, 능한"},
      {"voca": "confidentiality", "mean": "기밀, 비밀"},
      {"voca": "dispute", "mean": "분쟁, 논쟁"},
      {"voca": "objection", "mean": "반대, 이익"},
      {"voca": "define", "mean": "규정하다, 정의하다"},
      {"voca": "impression", "mean": "인상"},
      {"voca": "security", "mean": "보안, 안전, 보호"},
      {"voca": "option", "mean": "선택권"},
      {"voca": "proceed", "mean": "(일을)진행하다, 진척되다"},
      {"voca": "modify", "mean": "수정하다, 일부 변경하다"},
      {"voca": "narrow", "mean": "(범위 등을)좁히다"},
      {"voca": "bid", "mean": "입찰"},
      {"voca": "settle", "mean": "해결하다, 처리하다"},
      {"voca": "terminate", "mean": "끝내다, 종결시키다"},
      {"voca": "challenging", "mean": "도전적인, 힘든"},
      {"voca": "foundation", "mean": "토대, 기초"}
    ],
    [
      {"voca": "completely", "mean": "전적으로, 완전히"},
      {"voca": "refuse", "mean": "거절하다"},
      {"voca": "temporarily", "mean": "일시적으로\r\n(temporary 일시적인, 잠정적인, 임시고용인)"},
      {"voca": "dealer", "mean": "판매업자, 상인"},
      {"voca": "bulk", "mean": "대량의"},
      {"voca": "inventory", "mean": "재고품, 재고목록"},
      {"voca": "short", "mean": "부족한"},
      {"voca": "cost", "mean": "비용"},
      {"voca": "selection", "mean": "선택된 것, 정선품"},
      {"voca": "commercial", "mean": "상업의, 상업적인, 광고"},
      {"voca": "order", "mean": "주문하다, 주문, 주문품"},
      {"voca": "provide", "mean": "공급하다, 제공하다"},
      {"voca": "contact", "mean": "~와 연락하다,\r\n(상업적 목적으로)교섭하고 있는 사람"},
      {"voca": "invoice", "mean": "송장"},
      {"voca": "move", "mean": "옮기다, 움직이다, 조치, 수단;\r\n이동, 이사"},
      {"voca": "supply", "mean": "공급하다, 공급; (-s)비품, 소모품"},
      {"voca": "discount", "mean": "할인"},
      {"voca": "distribute", "mean": "배포하다, 배급하다"},
      {"voca": "acquisition", "mean": "인수; 구입한 것"},
      {"voca": "assure", "mean": "~에게 보장하다, ~을 안심시키다, 장담하다"},
      {
        "voca": "subject",
        "mean": "~의 영향을 받기 쉬운;\r\n(동의 등을)조건으로 하는,\r\n~에게(~을) 받게 하다"
      },
      {"voca": "seek", "mean": "구하다, 찾다"},
      {"voca": "satisfactory", "mean": "만족스러운"},
      {"voca": "confirmation", "mean": "확인, 확증"},
      {"voca": "unable", "mean": "~할 수 없는"},
      {"voca": "payment", "mean": "지불(금액),납입(금액)"},
      {"voca": "measure", "mean": "대책, 조치, 수단\r\n측정하다"},
      {"voca": "bargain", "mean": "특가품, 흥정"},
      {"voca": "stock", "mean": "재고; 주식"},
      {"voca": "affordability", "mean": "감당할 수 있는 비용"},
      {"voca": "clientele", "mean": "(집합적)고객들,\r\n(변호사,건축가 등의)모든 의뢰인"},
      {"voca": "acclaim", "mean": "호평, 찬사"},
      {"voca": "represent", "mean": "~을 대표하다"},
      {"voca": "rating", "mean": "등급, 평가"},
      {"voca": "encompass", "mean": "포함하다, 둘러싸다"},
      {"voca": "finalize", "mean": "마무리 짓다, 완결하다"},
      {"voca": "market", "mean": "시장"},
      {"voca": "retail", "mean": "소매"},
      {"voca": "commodity", "mean": "상품, 산물"},
      {"voca": "quote", "mean": "견적(액), 견적을 내다"},
      {"voca": "consignment", "mean": "위탁 판매(consign위탁하다)"}
    ],
    [
      {"voca": "fragile", "mean": "깨지기 쉬운"},
      {"voca": "perishable", "mean": "부패하기 쉬운"},
      {"voca": "deliver", "mean": "배달하다; (연설을)하다"},
      {"voca": "ensure", "mean": "확실하게 하다, 보장하다"},
      {"voca": "courier", "mean": "급송 택배, 운반인"},
      {"voca": "carton", "mean": "(큰)판지상자"},
      {"voca": "address", "mean": "주소,\r\n(어려운 문제 등을)처리하다,다루다"},
      {"voca": "shipment", "mean": "선적, (화물의)발송;\r\n수송품, 적하물"},
      {"voca": "particularly", "mean": "특히"},
      {"voca": "adequately", "mean": "적절히"},
      {"voca": "article", "mean": "물품, 물건; 기사, 논설"},
      {"voca": "efficient", "mean": "(기계, 방법 등이)효과적인,능률적인"},
      {"voca": "agency", "mean": "대행 회사, 대리점"},
      {"voca": "enclose", "mean": "~을 동봉하다; ~을 둘러싸다, 애워싸다"},
      {"voca": "careful", "mean": "조심스러운, 주의 깊은"},
      {"voca": "pick up", "mean": "~을 찾다; (사람,물건 등을) 도중에 태우다"},
      {"voca": "carry", "mean": "지니다; (물건을)팔다, 가게에 놓다"},
      {"voca": "attach", "mean": "붙이다, 접착하다, 첨부하다"},
      {"voca": "formerly", "mean": "이전에"},
      {"voca": "package", "mean": "소포, 꾸러미"},
      {"voca": "react", "mean": "반응하다, 대응하다"},
      {"voca": "content", "mean": "내용물"},
      {"voca": "convenience", "mean": "편의, 편리"},
      {"voca": "acknowledge", "mean": "인정하다; (편지 등의)수령을 알리다, 감사하다"},
      {"voca": "caution", "mean": "주의, 조심"},
      {"voca": "correspondence", "mean": "편지, 통신문"},
      {"voca": "separate", "mean": "분리하다; 분류하다"},
      {"voca": "remarkable", "mean": "현저한, 두드러진(markedly 현저하게 눈에 띄게)"},
      {"voca": "handle", "mean": "취급하다, 다루다"},
      {"voca": "warehouse", "mean": "창고, 저장소"},
      {"voca": "impose", "mean": "(세금 등을)부과하다"},
      {"voca": "storage", "mean": "보관소, 저장소"},
      {"voca": "detach", "mean": "분리하다, 떼다, (attach 붙이다)"},
      {"voca": "envelope", "mean": "봉투"},
      {"voca": "exclusion", "mean": "제외, 배제"},
      {"voca": "recipient", "mean": "수신자"},
      {"voca": "affix", "mean": "(우표 등을)붙이다"},
      {"voca": "incorrect", "mean": "부정확한"},
      {"voca": "oblige", "mean": "어쩔 수 없이 ~하게 하다,\r\n~에게 강요하다"},
      {"voca": "step", "mean": "단계; 조치, 수단"}
    ],
    [
      {"voca": "check in", "mean": "체크인하다, 숙박 수속을 하다"},
      {"voca": "compensate", "mean": "보상하다\r\n(compensation 보상)"},
      {"voca": "complimentary", "mean": "무료의, 우대의"},
      {"voca": "chef", "mean": "주방장"},
      {"voca": "container", "mean": "용기, 그릇"},
      {"voca": "elegant", "mean": "우아한, 고상한"},
      {"voca": "flavor", "mean": "맛, 풍미"},
      {
        "voca": "accommodate",
        "mean": "(건물 등이)~을 수용하다, 숙박시키다;(충분한 공간을) 제공하다\r\n(조건, 요구 등을)만족시키다"
      },
      {"voca": "available", "mean": "(사물이)이용 가능한;\r\n(사람이) 시간이 있는"},
      {"voca": "reception", "mean": "환영회; (호텔, 회사, 병원 등의)접수처"},
      {"voca": "in advance", "mean": "미리, 사전에"},
      {"voca": "refreshments", "mean": "다과, 가벼운 음식물"},
      {"voca": "make", "mean": "~을 하다, ~을 만들다"},
      {"voca": "cater", "mean": "(연회 등의)음식물을 공급하다"},
      {"voca": "reservation", "mean": "예약, 지정; 보호구역"},
      {"voca": "beverage", "mean": "음료"},
      {"voca": "confirm", "mean": "확인하다"},
      {"voca": "cancel", "mean": "취소하다"},
      {"voca": "rate", "mean": "요금"},
      {"voca": "conviniently", "mean": "편리하게"},
      {"voca": "decorate", "mean": "장식하다"},
      {"voca": "information", "mean": "정보, 자료"},
      {"voca": "retain", "mean": "유지하다, 보유하다"},
      {"voca": "atmosphere", "mean": "분위기, 환경"},
      {"voca": "cuisine", "mean": "(독특한)요리"},
      {"voca": "sequence", "mean": "순서, 차례"},
      {"voca": "extensive", "mean": "광범위한, 넓은"},
      {"voca": "prior", "mean": "전의, 먼저의"},
      {"voca": "book", "mean": "예약하다"},
      {"voca": "amenity", "mean": "편의 시설"},
      {"voca": "belongings", "mean": "소지품, 소유물"},
      {"voca": "entirely", "mean": "완전히"},
      {"voca": "ease", "mean": "완화시키다, 쉬움, 용이함"},
      {"voca": "ingredient", "mean": "재료, 성분"},
      {"voca": "sip", "mean": "음미하며 마시다, 홀짝거리다"},
      {"voca": "stir", "mean": "휘젓다, 뒤섞다"},
      {"voca": "choice", "mean": "선택물, 선택 사항, 선택"},
      {"voca": "complication", "mean": "복잡한 문제"},
      {"voca": "freshness", "mean": "신선함"},
      {"voca": "occupancy", "mean": "(호텔등의)이용률"}
    ],
    [
      {"voca": "decline", "mean": "감소, 하락,(초대,신청을)거절하다"},
      {"voca": "markedly", "mean": "현저하게, 눈에 띄게"},
      {"voca": "increase", "mean": "인상, 증가, 증가하다"},
      {"voca": "revenue", "mean": "수입"},
      {"voca": "projection", "mean": "예상(치)"},
      {"voca": "substantial", "mean": "상당한"},
      {"voca": "anticipate", "mean": "예상하다, 기대하다\r\n(anticipation 예상)"},
      {"voca": "significantly", "mean": "상당히, 두드러지게"},
      {"voca": "estimate", "mean": "추정하다, 추산하다, 추정(치), 추산"},
      {"voca": "shift", "mean": "옮기다, 이동하다, 변화, 교대근무"},
      {"voca": "fee", "mean": "요금, 수수료"},
      {"voca": "production", "mean": "생산량, 생산"},
      {"voca": "sale", "mean": "(-s)매출액, 매상고; (할인)판매"},
      {"voca": "impressive", "mean": "굉장한, 인상적인"},
      {"voca": "representative", "mean": "직원, 외판원; 대표자"},
      {"voca": "recent", "mean": "최근의"},
      {
        "voca": "exceed",
        "mean": "~을 초과하다\r\n(exceedingly 대단히, 몹시)\r\n(exceedably 넘을 수 있는)"
      },
      {"voca": "improvement", "mean": "향상"},
      {"voca": "employer", "mean": "고용주"},
      {"voca": "regular", "mean": "정기적인; 단골의"},
      {"voca": "summarize", "mean": "요약하다"},
      {"voca": "typically", "mean": "보통, 일반적으로"},
      {"voca": "whole", "mean": "전체의, 온전한"},
      {"voca": "growth", "mean": "성장, 발전"},
      {"voca": "figure", "mean": "총액, 합계 수"},
      {"voca": "steady", "mean": "꾸준한; 안정된"},
      {"voca": "frequent", "mean": "빈번한, 잦은"},
      {"voca": "achieve", "mean": "달성하다, 성취하다"},
      {"voca": "assumption", "mean": "추정, 산정, 가정"},
      {
        "voca": "share",
        "mean": "공유하다, 함께쓰다;\r\n(생각, 경험, 감정을 남과)함께 나누다\r\n몫, 지분"
      },
      {"voca": "incur", "mean": "(손실을)입다, (빚을)지다"},
      {"voca": "slightly", "mean": "약간"},
      {"voca": "profit", "mean": "수익, 이익"},
      {"voca": "reliant", "mean": "의존하는, 의지하는\r\n(reliantly 의지하여)"},
      {"voca": "illustrate", "mean": "분명히 보여주다, 설명하다\r\n(illustrate 설명,해설,삽화)"},
      {"voca": "inaccurate", "mean": "부정확한"},
      {"voca": "percentage", "mean": "비율, 백분율"},
      {"voca": "reduce", "mean": "줄이다, 감소시키다"},
      {"voca": "tend", "mean": "~하는 경향이 있다, ~하기 쉽다"}
    ],
    [
      {"voca": "audit", "mean": "회계 감사, 심사"},
      {"voca": "accounting", "mean": "회계"},
      {"voca": "budget", "mean": "예산"},
      {"voca": "financial", "mean": "재정의, 금전상의"},
      {"voca": "curtail", "mean": "~을 줄이다, 삭감하다\r\n(curtailment 단축)"},
      {"voca": "deficit", "mean": "적자, 부족액"},
      {"voca": "recently", "mean": "최근에"},
      {"voca": "substantially", "mean": "크게, 상당히\r\n(substantial 상당한, 재력이 있는)"},
      {"voca": "committee", "mean": "위원회"},
      {"voca": "frequently", "mean": "자주, 흔히"},
      {"voca": "capability", "mean": "능력, 역량"},
      {"voca": "proceeds", "mean": "수익금"},
      {"voca": "reimburse", "mean": "변제하다, 상환하다"},
      {"voca": "considerably", "mean": "상당히, 많이"},
      {"voca": "adequate", "mean": "충분한, 적절한\r\n(adequately 적절히, 충분히)"},
      {"voca": "total", "mean": "총계의, 전부의"},
      {"voca": "allocate", "mean": "할당하다, 배분하다\r\n(allocation 할당)"},
      {"voca": "inspector", "mean": "조사관, 감독관\r\n(inspect 검사하다)"},
      {"voca": "preferred", "mean": "선호되는, 우선의"},
      {"voca": "quarter", "mean": "사분기; 4분의1"},
      {"voca": "interrupt", "mean": "중단시키다, 방해하다\r\n(interruption 방해, 중지, 중단)"},
      {"voca": "browse", "mean": "흝어보다, 둘러보다"},
      {"voca": "prompt", "mean": "즉각적인; 신속한, 촉발하다, 유도하다 (promptly 신속히)"},
      {"voca": "deduct", "mean": "공제하다, 빼다\r\n(deduction 공제)"},
      {"voca": "measurement", "mean": "측정, 측량; 치수"},
      {"voca": "shorten", "mean": "단축하다, 짧게하다"},
      {"voca": "amend", "mean": "수정하다\r\n(amendable 개정할 수 있는)"},
      {"voca": "calculate", "mean": "계산하다, 산출하다"},
      {"voca": "exempt", "mean": "면제된, ~이 없는\r\n(exemption 면제)"},
      {"voca": "deficient", "mean": "부족한, 불충분한"},
      {"voca": "compare", "mean": "비교하다"},
      {"voca": "fortunate", "mean": "운 좋은"},
      {"voca": "expenditure", "mean": "지출, 비용"},
      {"voca": "accurately", "mean": "정확하게"},
      {"voca": "worth", "mean": "~의 가치가 있는, (얼마)어치, 가치"},
      {"voca": "excess", "mean": "초과, 초과량"},
      {"voca": "fiscal", "mean": "회계의, 재정상의"},
      {"voca": "incidental", "mean": "부수적인"},
      {"voca": "inflation", "mean": "물가상승, 인플레이션, 통화팽창"},
      {"voca": "liable", "mean": "책임져야 할; ~하기 쉬운"},
      {"voca": "spend", "mean": "~을 쓰다, 소비하다"},
      {"voca": "turnover", "mean": "총 매상고, 거래액; 이직률"}
    ],
    [
      {"voca": "announce", "mean": "발표하다"},
      {"voca": "interested", "mean": "관련 있는; 관심이 있는"},
      {"voca": "active", "mean": "적극적인, 활발한"},
      {"voca": "accept", "mean": "수락하다, 승낙하다"},
      {"voca": "foresee", "mean": "예견하다, 예감하다"},
      {"voca": "expansion", "mean": "확장, 팽창"},
      {"voca": "relocate", "mean": "(공장 등을)이전하다"},
      {"voca": "competitor", "mean": "경쟁업체, 경쟁자"},
      {"voca": "asset", "mean": "자산"},
      {"voca": "contribute", "mean": "기여하다, 공헌하다"},
      {"voca": "dedicated", "mean": "(목표 등에)전념하는, 헌신적인"},
      {"voca": "misplace", "mean": "잃어버리다, 위치를 잘못 잡다"},
      {"voca": "considerable", "mean": "(정도나 양이)상당한"},
      {"voca": "last", "mean": "지속되다"},
      {"voca": "emerge", "mean": "부상하다, 나타나다\r\n(merge 합병하다)"},
      {"voca": "grow", "mean": "성장하다, 성장시키다, 증가시키다"},
      {"voca": "select", "mean": "선발하다, 선택하다"},
      {"voca": "merge", "mean": "합병하다, 병합하다"},
      {"voca": "imply", "mean": "암시하다, 넌지시 나타내다, 의미하다"},
      {"voca": "vital", "mean": "필수적인"},
      {
        "voca": "persist",
        "mean": "(집요하게)계속하다, 계속되다, 지속되다\r\n(continue 계속되다, 계속하다)"
      },
      {"voca": "independent", "mean": "독립적인, 독자적인"},
      {"voca": "force", "mean": "세력"},
      {"voca": "establish", "mean": "설립하다"},
      {"voca": "initiate", "mean": "(사업 등을) 착수하다, 시작하다\r\n(commence 시작하다)"},
      {
        "voca": "enhance",
        "mean":
            "(질 등을) 향상시키다, 높이다, 강화하다\r\n(strengthen 강화하다)\r\n(reinforce 보강하다, 강화하다)"
      },
      {"voca": "renowned", "mean": "저명한, 유명한, 명성이 있는"},
      {"voca": "informed", "mean": "정보에 근거한\r\n(inform 알리다, 통지하다)"},
      {"voca": "minutes", "mean": "회의록"},
      {
        "voca": "waive",
        "mean": "(규칙 등을)적용하지 않다,\r\n(권리,청구등을)포기하다\r\n(abandon 버리다, 단념하다, 그만두다)"
      },
      {"voca": "reach", "mean": "(치수,양 등이)~에 달하다;\r\n~에 도착하다"},
      {"voca": "authority", "mean": "권한; 당국"},
      {
        "voca": "acquire",
        "mean": "매입하다, 취득하다\r\n(inquire 묻다)\r\n(inquiry 조사, 문의)"
      },
      {"voca": "surpass", "mean": "~을 능가하다, 넘어서다"},
      {"voca": "run", "mean": "~을 운영하다, 경영하다"},
      {
        "voca": "improbable",
        "mean": "사실이라고 생각할 수 없는,\r\n일어날 것 같지 않은\r\n(probable 있음직한, 일어날것같은)"
      },
      {"voca": "edge", "mean": "우위, 유리함; 가장자리, 끝"},
      {
        "voca": "simultaneously",
        "mean": "동시에\r\n(coincidentally 우연히 일치하게 동시발생적으로)"
      },
      {"voca": "reveal", "mean": "밝히다, 누설하다"},
      {"voca": "productivity", "mean": "생산성"},
      {"voca": "uncertain", "mean": "확신이 없는, 불확실한"},
      {"voca": "premier", "mean": "으뜸의, 첫째의"}
    ],
    [
      {"voca": "agenda", "mean": "의제, 의사일정"},
      {"voca": "convene", "mean": "(회원 등이)모이다, (회의가)개최되다\r\n(convener 의장,소집자)"},
      {"voca": "refute", "mean": "부인하다, 반박하다\r\n(refutation 반박, 반론)"},
      {"voca": "coordination", "mean": "조정"},
      {"voca": "unanimous", "mean": "만장일치의, 동의하는\r\n(unanimously  만장일치로)"},
      {"voca": "convince", "mean": "납득시키다, 확신시키다"},
      {"voca": "consensus", "mean": "여론, 일치된 의견"},
      {"voca": "defer", "mean": "연기하다, 미루다\r\n(differ 다르다)"},
      {"voca": "usually", "mean": "보통, 일반적으로"},
      {"voca": "reschedule", "mean": "일정을 바꾸다"},
      {"voca": "meeting", "mean": "회의"},
      {"voca": "determine", "mean": "알아내다; 결정하다, 확정하다"},
      {
        "voca": "report",
        "mean": "보고하다; 출두하다,\r\n(직장,회의 등에 도착을)알리다,\r\n보고서; 보도, 기록"
      },
      {"voca": "comment", "mean": "논평하다, 언급하다"},
      {"voca": "phase", "mean": "단계"},
      {"voca": "approve", "mean": "승인하다, 찬성하다"},
      {"voca": "enclosed", "mean": "동봉된"},
      {"voca": "easy", "mean": "쉬운, 용이한"},
      {"voca": "record", "mean": "기록; 경력, 이력, 기록하다"},
      {"voca": "suggestion", "mean": "제안"},
      {"voca": "attention", "mean": "주의, 경청"},
      {"voca": "object", "mean": "반대하다"},
      {
        "voca": "coincidentally",
        "mean": "우연히, 일치하게, 동시 발생적으로\r\n(coincident 일치하는)"
      },
      {"voca": "crowded", "mean": "붐비는, 복잡한"},
      {"voca": "undergo", "mean": "겪다, 거치다, 경험하다"},
      {"voca": "outcome", "mean": "결과 (=consequence)"},
      {"voca": "narrowly", "mean": "주의 깊게, 좁게; 가까스로, 간신히, 겨우"},
      {"voca": "differ", "mean": "의견을 달리하다, 다르다"},
      {"voca": "discuss", "mean": "논의하다, 토론하다"},
      {"voca": "give", "mean": "(연설, 수업 등을)하다"},
      {"voca": "brief", "mean": "~에게 간단히 설명하다, 브리핑하다"},
      {
        "voca": "distract",
        "mean": "(주의를)산만하게 하다, 빗기게 하다(distraction 주의산만, 방심)"
      },
      {"voca": "emphasis", "mean": "강조, 중점"},
      {"voca": "press", "mean": "언론(계),보도기관, 누르다"},
      {"voca": "organize", "mean": "준비하다, 조직하다, 정리하다"},
      {"voca": "mention", "mean": "언급하다"},
      {"voca": "persuasive", "mean": "설득력 있는"},
      {"voca": "understanding", "mean": "이해심 있는"},
      {"voca": "adjourn", "mean": "(회의 등을)휴회하다"},
      {"voca": "constructive", "mean": "건설적인"},
      {"voca": "preside", "mean": "(회의의)사회를 보다, ~의 의장을 맡아보다"},
      {"voca": "irrelevant", "mean": "관계가 없는, 무관한\r\n(relevant 관계가 있는)"},
      {"voca": "constraint", "mean": "제한(=restriction)"}
    ],
    [
      {"voca": "host", "mean": "(대회 등을)주최하다"},
      {"voca": "annual", "mean": "매년의"},
      {"voca": "purpose", "mean": "목적, 의도"},
      {"voca": "enroll", "mean": "등록하다"},
      {"voca": "lecture", "mean": "강의, 강연"},
      {"voca": "participant", "mean": "참가자"},
      {"voca": "attend", "mean": "참석하다, 출석하다"},
      {"voca": "encourage", "mean": "장려하다, 복돋아주다"},
      {"voca": "leave", "mean": "휴가, 떠나다, 남기다"},
      {"voca": "recommendation", "mean": "추천사항, 추천"},
      {"voca": "conference", "mean": "회의, 회담"},
      {"voca": "schedule", "mean": "~을 예정하다"},
      {"voca": "include", "mean": "포함하다"},
      {"voca": "result", "mean": "결과,(~의 결과로)되다"},
      {"voca": "register", "mean": "등록하다"},
      {"voca": "require", "mean": "요구하다"},
      {"voca": "grateful", "mean": "고마워하는, 감사하는"},
      {"voca": "overtime", "mean": "초과근무, 야근"},
      {"voca": "responsibility", "mean": "부담, 책임, 의무"},
      {
        "voca": "assent",
        "mean":
            "찬성하다, 승인, 동의\r\n(approval 승인)\r\n(approve 찬성하다)\r\n(prove 증명하다)"
      },
      {"voca": "regard", "mean": "~을 -으로 간주하다, 여기다,\r\n관심,배려"},
      {"voca": "tentative", "mean": "임시적인, 잠정적인"},
      {"voca": "welcome", "mean": "반가운, 기꺼이 받아들여지는"},
      {"voca": "function", "mean": "행사, 연회"},
      {"voca": "commence", "mean": "시작되다"},
      {"voca": "objective", "mean": "목표, 목적"},
      {"voca": "excited", "mean": "신이 난, 들뜬"},
      {"voca": "reimbursement", "mean": "상환, 변제, 배상"},
      {"voca": "treatment", "mean": "대우, 처우"},
      {"voca": "honor", "mean": "존경, 명예"},
      {"voca": "emphasize", "mean": "강조하다"},
      {"voca": "entry", "mean": "(경기 등의)참가자, 출품물"},
      {"voca": "bonus", "mean": "상여금, 보너스"},
      {"voca": "salary", "mean": "급여"},
      {"voca": "earn", "mean": "(금전 등을)벌다; (평판을)받다, 얻다"},
      {"voca": "arise", "mean": "(문제 등이)발생하다, 일어나다 = occur"},
      {"voca": "labor", "mean": "노동"},
      {"voca": "union", "mean": "노동조합"},
      {"voca": "existing", "mean": "기존의, 현행의"},
      {
        "voca": "exploit",
        "mean": "착취하다, 부당하게 이용하다\r\n(exploitation 개발,개척,약탈,착취)"
      }
    ],
    [
      {"voca": "appoint", "mean": "임명하다, 지명하다"},
      {"voca": "appraisal", "mean": "평가"},
      {"voca": "promote", "mean": "승진시키다; 촉진하다"},
      {"voca": "skilled", "mean": "숙련된, 노련한"},
      {"voca": "radically", "mean": "완전히, 철저히, 근본적으로\r\n(radical 근본적인, 과격한)"},
      {"voca": "exceptional", "mean": "뛰어난, 예외적인\r\n(exception 예외, 이의, 반대)"},
      {"voca": "appreciation", "mean": "감사"},
      {"voca": "evaluate", "mean": "평가하다"},
      {"voca": "suggest", "mean": "제안하다, 추천하다"},
      {"voca": "preference", "mean": "선호"},
      {"voca": "management", "mean": "경영진, 경영"},
      {"voca": "predict", "mean": "예측하다"},
      {"voca": "transfer", "mean": "보내다; 전근시키다"},
      {"voca": "award", "mean": "상\r\n(reward 보상하다, 포상,보상)"},
      {"voca": "mandatory", "mean": "의무적인"},
      {"voca": "competent", "mean": "유능한, 능숙한\r\n(competence 능력)"},
      {"voca": "performance", "mean": "실적,성과; 공연,연주, 연기"},
      {"voca": "reward", "mean": "~에 보답하다, 보상하다, 포상,보상\r\n(award 상)"},
      {"voca": "search", "mean": "찾기, 수색, 조사"},
      {"voca": "inexperienced", "mean": "경험없는, 미숙한"},
      {"voca": "early", "mean": "시간상 이른, 조기의"},
      {"voca": "designate", "mean": "지명하다, 지정하다"},
      {"voca": "executive", "mean": "경영의,관리의"},
      {"voca": "dedication", "mean": "헌신"},
      {
        "voca": "unanimously",
        "mean": "만장일치로\r\n(unanimous 만장일치의)\r\n(anonymously 익명으로, 특색없이)"
      },
      {"voca": "progress", "mean": "진행, 진척, 진전, 진보하다, 발전하다"},
      {"voca": "congratulate", "mean": "축하하다"},
      {"voca": "dismiss", "mean": "해임하다, 해고하다"},
      {"voca": "independence", "mean": "독립성"},
      {"voca": "participation", "mean": "참여, 참가, 가입"},
      {"voca": "praise", "mean": "칭찬"},
      {"voca": "accomplishment", "mean": "성과,업적"},
      {"voca": "deliberation", "mean": "토의, 심의, 숙고\r\n(deliberate 고의의, 숙고하다)"},
      {"voca": "leadership", "mean": "리더십, 지도력"},
      {"voca": "retire", "mean": "퇴직하다, 은퇴하다"},
      {"voca": "nomination", "mean": "임명, 지명"},
      {
        "voca": "reorganize",
        "mean": "재편성하다, 재조직하다\r\n(recognize 인식하다)\r\n(organize 조직하다)"
      },
      {"voca": "serve", "mean": "근무하다, 일하다"},
      {"voca": "encouragement", "mean": "격려"},
      {"voca": "resignation", "mean": "사임, 사직, 사직서"},
      {"voca": "strictly", "mean": "엄격히"}
    ],
    [
      {"voca": "congestion", "mean": "(교통의)체증, 혼잡\r\n(congest 혼잡하게 하다)"},
      {"voca": "alleviate", "mean": "완화하다"},
      {"voca": "divert", "mean": "우회시키다, 다른 곳으로 돌리다"},
      {"voca": "detour", "mean": "우회"},
      {"voca": "fuel", "mean": "연료"},
      {"voca": "malfunction", "mean": "오작동, 기능불량"},
      {"voca": "permit", "mean": "허락하다, 허가증"},
      {"voca": "transportation", "mean": "교통(수단), 운송 수단"},
      {"voca": "opportunity", "mean": "기회"},
      {"voca": "clearly", "mean": "명확히"},
      {"voca": "ongoing", "mean": "계속 진행 중인"},
      {"voca": "detailed", "mean": "상세한"},
      {"voca": "alternative", "mean": "대안, 대체, 다른, 대신의"},
      {"voca": "obtain", "mean": "획득하다, 얻다"},
      {"voca": "designated", "mean": "지정된"},
      {"voca": "intersection", "mean": "교차로, 교차지점"},
      {"voca": "equip", "mean": "갖추다, 설비하다"},
      {"voca": "commute", "mean": "통근하다"},
      {"voca": "downtown", "mean": "시내에서, 도심지로"},
      {"voca": "automotive", "mean": "자동차의"},
      {"voca": "closure", "mean": "폐쇄"},
      {"voca": "vehicle", "mean": "차량, 운송 수단"},
      {"voca": "platform", "mean": "승강장"},
      {"voca": "official", "mean": "공무원, 관리, 공식적인"},
      {"voca": "transit", "mean": "교통, 수송, 통과하다"},
      {"voca": "fare", "mean": "교통요금"},
      {"voca": "expense", "mean": "비용, 지출"},
      {"voca": "trust", "mean": "신뢰, 신임, 믿다, 신뢰하다"},
      {"voca": "head", "mean": "(~의 방향으로)나아가다, 향하게 하다"},
      {"voca": "drive", "mean": "(차 등을)운전하다, 타고가다, 조종하다"},
      {"voca": "fine", "mean": "벌금"},
      {"voca": "pass", "mean": "지나가다, 통과하다"},
      {"voca": "securely", "mean": "(매듭 등이)단단하게, 튼튼하게"},
      {"voca": "prominently", "mean": "눈에 잘 띄게, 두드러지게\r\n(prominent 눈에 띄는)"},
      {"voca": "reserved", "mean": "예약된, 예약한; 지정된"},
      {"voca": "average", "mean": "평균치, 평균"},
      {"voca": "collision", "mean": "충돌"},
      {"voca": "tow", "mean": "견인하다"},
      {"voca": "reverse", "mean": "뒤의, 반대의"},
      {
        "voca": "obstruct",
        "mean": "(전망 등을)가리다, 차단하다;\r\n(도로 등을)막다\r\n(obstruction 장애물, 방해물)"
      }
    ],
    [
      {"voca": "delinquent", "mean": "(세금 등이)연체된, 미불의"},
      {"voca": "overdue", "mean": "(지불,반납 등의)기한이 지난, 지불 기한이 넘은"},
      {"voca": "regrettably", "mean": "유감스럽게도"},
      {"voca": "balance", "mean": "잔고, 차감 잔액"},
      {"voca": "deposit", "mean": "입금하다, 예금하다"},
      {"voca": "investigation", "mean": "조사 (investigate 연구하다, 조사하다)"},
      {"voca": "account", "mean": "계좌; 설명; 고려"},
      {"voca": "statement", "mean": "명세서, 성명서"},
      {"voca": "amount", "mean": "액수, 양"},
      {"voca": "withdrawal", "mean": "(예금의)인출"},
      {"voca": "previously", "mean": "이전에"},
      {"voca": "due", "mean": "만기가 된, 지불 기일이 된;\r\n(금전 등이)~에게 마땅히 지급되어야 할"},
      {"voca": "receive", "mean": "받다, 수취하다"},
      {"voca": "expect", "mean": "예상하다, 기대하다"},
      {"voca": "certificate", "mean": "증명서, 증서"},
      {"voca": "document", "mean": "서류, 문서"},
      {"voca": "spending", "mean": "소비; 지출"},
      {"voca": "successfully", "mean": "성공적으로"},
      {"voca": "bill", "mean": "~에게 청구서를 보내다, 청구서, 계산서"},
      {"voca": "pleasure", "mean": "즐거움, 기쁜, 영광"},
      {"voca": "study", "mean": "연구"},
      {"voca": "summary", "mean": "요약, 개요\r\n(emphasize 강조하다)"},
      {"voca": "temporary", "mean": "임시의"},
      {"voca": "lower", "mean": "(양,가격을)줄이다"},
      {"voca": "transaction", "mean": "거래, 업무"},
      {"voca": "double", "mean": "두배로 만들다"},
      {"voca": "identification", "mean": "신분증, 신분 증명서"},
      {"voca": "dissatisfaction", "mean": "불만, 불평"},
      {"voca": "in common", "mean": "공통으로, 공동으로"},
      {"voca": "interest", "mean": "관심; 권리; 이자"},
      {"voca": "reject", "mean": "거절하다, 거부하다"},
      {"voca": "relation", "mean": "관계"},
      {
        "voca": "tentatively",
        "mean": "임시로, 시험적으로\r\n(tentative 시험적인, 임시의, 가설)"
      },
      {"voca": "alternatively", "mean": "그렇지 않으면, 그 대신에"},
      {"voca": "attentive", "mean": "주의 깊은, 세심한"},
      {"voca": "convert", "mean": "전환하다, 변환하다"},
      {"voca": "heavily", "mean": "몹시, 심하게"},
      {"voca": "loan", "mean": "대출, 대출금"},
      {"voca": "unexpected", "mean": "예기치 않은"},
      {"voca": "cash", "mean": "현금으로 바꾸다"},
      {"voca": "mortgage", "mean": "(담보)대출"},
      {"voca": "payable", "mean": "지불해야 하는"},
      {"voca": "personal", "mean": "개인의"}
    ],
    [
      {"voca": "investment", "mean": "투자, 투자금"},
      {
        "voca": "incrative",
        "mean":
            "수익성 있는, 돈벌이가 되는\r\n(profit, earning, gainings 이익)\r\n(income 수입, 소득)"
      },
      {"voca": "inherently", "mean": "본질적으로\r\n(inherent 본래 갖추어져 있는, 고유의)"},
      {"voca": "secure", "mean": "확보하다, 얻어 내다;\r\n안전하게 지키다, 고정시키다"},
      {
        "voca": "foreseeable",
        "mean": "예견할 수 있는\r\n(oversee 감독하다)\r\n(overseas 외국의)"
      },
      {"voca": "innate", "mean": "타고난"},
      {"voca": "property", "mean": "재산"},
      {"voca": "on behalf of", "mean": "~을 대신해서"},
      {"voca": "lease", "mean": "임대차(계약)"},
      {"voca": "sponsor", "mean": "후원하다, 후원자"},
      {"voca": "propose", "mean": "제안하다"},
      {
        "voca": "support",
        "mean": "후원, 원조, 지지, 지원하다,\r\n후원하다; 살게하다,\r\n(생명, 기력 등을)유지하다"
      },
      {"voca": "distributuion", "mean": "분배, 배급"},
      {"voca": "consider", "mean": "고려하다"},
      {"voca": "nearly", "mean": "거의, 대략"},
      {"voca": "consent", "mean": "동의, 허락, 동의하다\r\n(consentaneous일치하는)"},
      {"voca": "gratitude", "mean": "고마움, 감사"},
      {"voca": "consult", "mean": "상의하다, 상담하다"},
      {"voca": "advice", "mean": "조언, 충고"},
      {"voca": "partially", "mean": "부분적으로, 일부분은"},
      {"voca": "evident", "mean": "분명한, 명백한,"},
      {"voca": "reliability", "mean": "신뢰도, 믿음직함"},
      {"voca": "cautious", "mean": "조심하는, 신중한"},
      {"voca": "insight", "mean": "식견, 통찰력"},
      {"voca": "portfolio", "mean": "포트폴리오, 투자 자산 구성"},
      {"voca": "possible", "mean": "가능한, 있음직한"},
      {
        "voca": "speculation",
        "mean": "추측\r\n(speculate, suppose, guess, infer 추측하다)"
      },
      {"voca": "solely", "mean": "오로지, 혼자서, 전적으로"},
      {"voca": "entrepreneur", "mean": "사업가"},
      {"voca": "eventually", "mean": "결국, 마침내"},
      {"voca": "shareholder", "mean": "주주"},
      {"voca": "outlook", "mean": "전망"},
      {"voca": "stability", "mean": "안정, 안정성"},
      {"voca": "bond", "mean": "채권"},
      {
        "voca": "depreciation",
        "mean": "가치 하락, 화폐의 구매력 저하\r\n(depreciate : ~의 가치를 떨어뜨리다, 가치가 떨어지다)"
      },
      {"voca": "increasing", "mean": "증가하는"},
      {"voca": "prevalent", "mean": "유행하고 있는, 널리 퍼진\r\n(prevalence 보급, 유행)"},
      {"voca": "rapid", "mean": "빠른, 신속한"},
      {"voca": "unprecedented", "mean": "전례 없는\r\n(precedented 전례가 있는)"},
      {"voca": "yield", "mean": "(이윤을) 가져오다, 산출하다"}
    ],
    [
      {"voca": "furnished", "mean": "가구가 비치된"},
      {"voca": "residence", "mean": "거주지, 주택"},
      {"voca": "spacious", "mean": "(공간이)넓은"},
      {"voca": "drape", "mean": "(방 등을 커튼 등으로)장식하다"},
      {
        "voca": "unoccupied",
        "mean": "(집 등이)비어 있는, 사람이 살지 않는\r\n(occupy 차지하다, 점유하다)"
      },
      {"voca": "renovation", "mean": "수리, 개조"},
      {"voca": "appropriate", "mean": "적당한, 적합한(appropriately 적합하게)"},
      {"voca": "delay", "mean": "연기하다, ~을 뒤로 미루다"},
      {"voca": "community", "mean": "지역 사회, 공동체"},
      {"voca": "construction", "mean": "건설, 건축"},
      {"voca": "repair", "mean": "수리하다"},
      {"voca": "currently", "mean": "현재"},
      {"voca": "regularly", "mean": "정기적으로"},
      {"voca": "arrange", "mean": "배열하다, 정돈하다"},
      {"voca": "location", "mean": "장소, 위치"},
      {
        "voca": "restore",
        "mean": "복구하다, 회복시키다\r\n(recovery 회복, recover되찾다, 회복하다)"
      },
      {
        "voca": "presently",
        "mean":
            "현재\r\n(present, current현재의)\r\n(latest, recent, up to date 최근의)"
      },
      {"voca": "numerous", "mean": "많은"},
      {"voca": "abandon", "mean": "그만두다; 버리다(abondonment 버림, 포기)"},
      {"voca": "contractor", "mean": "계약자, 도급업자"},
      {"voca": "develop", "mean": "개발하다"},
      {"voca": "maintain", "mean": "유지하다, 관리하다"},
      {"voca": "densely", "mean": "빽빽이, 밀집하여"},
      {"voca": "prepare", "mean": "준비하다, 채비를 갖추다"},
      {"voca": "finally", "mean": "결국, 마침내"},
      {"voca": "district", "mean": "지역, 지구"},
      {"voca": "renewal", "mean": "재개발"},
      {"voca": "compulsory", "mean": "의무적인"},
      {"voca": "interfere", "mean": "방해하다, 해치다"},
      {"voca": "relocation", "mean": "이전, 재배치"},
      {"voca": "totally", "mean": "완전히, 전적으로"},
      {"voca": "actually", "mean": "실제로, 사실은"},
      {"voca": "architect", "mean": "건축가"},
      {"voca": "enlarge", "mean": "확장하다, 확대하다"},
      {"voca": "install", "mean": "설치하다, 장치하다"},
      {"voca": "permanent", "mean": "영구적인"},
      {"voca": "suppose", "mean": "생각하다, 추측하다(guess, infer 추측하다)"},
      {"voca": "adjacent", "mean": "인접한"},
      {"voca": "consist", "mean": "구성되다, 이루어지다"},
      {"voca": "utility", "mean": "공공시설; 공공요금"}
    ],
    [
      {"voca": "conserve", "mean": "보전하다, 유지하다"},
      {"voca": "chance", "mean": "가능성, 기회"},
      {"voca": "forecast", "mean": "(날씨의)예보"},
      {"voca": "waste", "mean": "쓰레기, 폐기물"},
      {"voca": "dispose", "mean": "처분하다, 처리하다"},
      {"voca": "recycling", "mean": "재활용"},
      {"voca": "clear", "mean": "맑게 갠; 명백한, 분명한\r\n또렷하게, 완전히; 떨어져서"},
      {"voca": "damage", "mean": "피해, 손해, 손상시키다"},
      {"voca": "significant", "mean": "상당한; 중대한, 중요한"},
      {"voca": "solution", "mean": "해결책"},
      {"voca": "occur", "mean": "(일이)발생하다, 생기다(happen, take place)"},
      {"voca": "ideal", "mean": "이상적인"},
      {
        "voca": "preserve",
        "mean": "보존하다, 보호하다(=conserve, maintain, retain, keep)"
      },
      {"voca": "aid", "mean": "원조, 돕다"},
      {"voca": "excessive", "mean": "지나친, 과도한(excess 초과, 초과량)"},
      {"voca": "intensively", "mean": "집중적으로( intense 격렬한)"},
      {"voca": "vary", "mean": "다르다, 다양하다"},
      {"voca": "pleasing", "mean": "즐거운, 기분 좋은, 만족스러운"},
      {"voca": "mark", "mean": "점수, 평점, 표시, 축하하다"},
      {"voca": "inaccessible", "mean": "접근이 불가능한, 이용이 불가능한"},
      {"voca": "disturb", "mean": "방해하다"},
      {"voca": "pollutant", "mean": "오염물질"},
      {"voca": "emission", "mean": "배기가스, 방출"},
      {"voca": "dense", "mean": "빽빽한, 밀집한"},
      {"voca": "environmental", "mean": "환경적인"},
      {"voca": "consistent", "mean": "일치하는, 지속적인, 한결같은"},
      {"voca": "leak", "mean": "누출, 누출량"},
      {"voca": "organization", "mean": "단체"},
      {"voca": "continually", "mean": "계속해서"},
      {"voca": "contaminate", "mean": "오염시키다(=pollution)"},
      {"voca": "disaster", "mean": "재난"},
      {"voca": "discharge", "mean": "방출하다"},
      {"voca": "resource", "mean": "자원, 자료"},
      {"voca": "prominent", "mean": "유명한, 두드러진"},
      {"voca": "deplete", "mean": "고갈시키다(depletion 고갈)"},
      {"voca": "purify", "mean": "정화시키다"},
      {"voca": "endangered", "mean": "멸종 위기에 처한"},
      {"voca": "extinction", "mean": "멸종"},
      {"voca": "drought", "mean": "가뭄"},
      {"voca": "inflict", "mean": "(고통,피해를)입히다, 가하다"},
      {"voca": "migration", "mean": "이동, 이주"},
      {"voca": "ecology", "mean": "생태, 자연환경"},
      {"voca": "habitat", "mean": "(동, 식물의)서식지"}
    ],
    [
      {"voca": "fatigue", "mean": "피로"},
      {"voca": "checkup", "mean": "건강 진단"},
      {"voca": "symtom", "mean": "증상"},
      {"voca": "physician", "mean": "내과의사"},
      {"voca": "diagnosis", "mean": "진단"},
      {"voca": "prescribe", "mean": "(약을)처방하다, 규정하다"},
      {"voca": "recovery", "mean": "회복, 쾌유"},
      {"voca": "recognize", "mean": "인정하다, 알아보다\r\n(organize 조직하다)"},
      {"voca": "join", "mean": "~에 가입하다"},
      {"voca": "comprehensive", "mean": "종합적인, 포괄적인"},
      {"voca": "participate", "mean": "참여하다, 참가하다"},
      {"voca": "recommend", "mean": "권고하다, 추천하다"},
      {"voca": "necessary", "mean": "필요한"},
      {"voca": "ability", "mean": "능력"},
      {"voca": "operation", "mean": "수술"},
      {"voca": "cleanliness", "mean": "청결"},
      {"voca": "duration", "mean": "지속 기간, 지속"},
      {"voca": "examination", "mean": "진찰, 검사"},
      {"voca": "eliminate", "mean": "제거하다(elimination 제거)"},
      {"voca": "easily", "mean": "쉽게"},
      {"voca": "dental", "mean": "치과의"},
      {"voca": "dietary", "mean": "식이 요법의, 규정식의"},
      {"voca": "related", "mean": "관련된"},
      {"voca": "transmit", "mean": "전염시키다(transmittable 전염가능한, 유전가능한)"},
      {"voca": "periodically", "mean": "주기적으로"},
      {"voca": "reaction", "mean": "반응"},
      {"voca": "simple", "mean": "단순한"},
      {"voca": "coverage", "mean": "(보험의)보상 범위; (신문 등의)보도, 취재범위"},
      {"voca": "exposure", "mean": "노출"},
      {"voca": "pharmaceutical", "mean": "제약의, 약학의"},
      {"voca": "premium", "mean": "보험료"},
      {"voca": "relieve", "mean": "완화시키다"},
      {"voca": "combination", "mean": "결합, 연합"},
      {"voca": "conscious", "mean": "알고 있는, 자각하고 있는\r\n(consciousness : 의식)"},
      {"voca": "deprivation", "mean": "박탈, 상실(deprivative 박탈하는, 빼앗는)"},
      {"voca": "health", "mean": "건강; (사회,기관의,)번영,안녕"},
      {"voca": "induce", "mean": "유발하다 (reduce줄이다, 낮추다)"},
      {"voca": "insurance", "mean": "보험"},
      {"voca": "nutrition", "mean": "영양"},
      {"voca": "prevention", "mean": "예방(prevent 예방하다, 방해하다)"},
      {"voca": "susceptible", "mean": "~에 감염되기 쉬운, 영향 받기 쉬운"}
    ]
  ];

  static int getDayCount() {
    return days.length;
  }

  static List<Map<String, String>> getDay(int day) {
    return days[day];
  }

  static getCountOfDay(int day) {
    return days[day].length;
  }
}
